// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN7nob4zGCbSG5llijiATUIG0sVdiUe2Q',
    appId: '1:967640157497:web:50adb3101c84109923ece8',
    messagingSenderId: '967640157497',
    projectId: 'fir-news-app-ad554',
    authDomain: 'fir-news-app-ad554.firebaseapp.com',
    storageBucket: 'fir-news-app-ad554.appspot.com',
    measurementId: 'G-5RJ5MSSCBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDJAZSgoYOZWPgE9hVyhf7FX3OrfCR1CI',
    appId: '1:967640157497:android:6cd1129bbc59af3d23ece8',
    messagingSenderId: '967640157497',
    projectId: 'fir-news-app-ad554',
    storageBucket: 'fir-news-app-ad554.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhnxs0vbq62-WhP2x9cF3XcTojptVjhdI',
    appId: '1:967640157497:ios:a5cfdeeaeecb59ac23ece8',
    messagingSenderId: '967640157497',
    projectId: 'fir-news-app-ad554',
    storageBucket: 'fir-news-app-ad554.appspot.com',
    iosClientId: '967640157497-cqnmquskc5iio7htjd98gse1dcen3cr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhnxs0vbq62-WhP2x9cF3XcTojptVjhdI',
    appId: '1:967640157497:ios:a5cfdeeaeecb59ac23ece8',
    messagingSenderId: '967640157497',
    projectId: 'fir-news-app-ad554',
    storageBucket: 'fir-news-app-ad554.appspot.com',
    iosClientId: '967640157497-cqnmquskc5iio7htjd98gse1dcen3cr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );
}
